export const APP_BLOCKLIST: string[] = [
  "Safari.app",
  "FaceTime.app",
  "Mail.app",
  "Messages.app",
  "Calendar.app",
  "Contacts.app",
  "Notes.app",
  "Reminders.app",
  "Photos.app",
  "Maps.app",
  "Music.app",
  "Podcasts.app",
  "TV.app",
  "Books.app",
  "Freeform.app",
  "Preview.app",
  "TextEdit.app",
  "Stickies.app",
  "Calculator.app",
  "Dictionary.app",
  "Chess.app",
  "Image Capture.app",
  "Photo Booth.app",
  "QuickTime Player.app",
  "System Settings.app",
  "System Preferences.app",
  "App Store.app",
  "Activity Monitor.app",
  "Terminal.app",
  "Console.app",
  "Disk Utility.app",
  "Keychain Access.app",
  "Migration Assistant.app",
  "Time Machine.app",
  "VoiceOver.app",
  "iMovie.app",
  "GarageBand.app",
  "Pages.app",
  "Numbers.app",
  "Keynote.app",
];
